version: 0.1

phases:
  install:
    commands:
      - yum install -y docker
  pre_build:
    commands:
      - /etc/init/docker start
  build:
    commands:
      - mvn clean package
      - docker build -t hello-world .