version: 0.1

phases:
  install:
    commands:
      - chmod +x codebuild_install.sh
      - ./codebuild_install.sh
  build:
    commands:
      - mvn clean package
      - docker build -t hello-world .