version: 0.1

phases:
  install:
    commands:
      - chmod +x codebuild_install.sh
      - ./codebuild_install.sh
  build:
    commands:
      - /usr/bin/apache-maven-3.3.9/bin/mvn clean package
      - docker build -t hello-world .